### ISSUE TITLE
va sources

### ISSUE THREAD

**Issue by github-gsjb** [mimajiushi/express-parent#5]
联系我

**Comment by mimajiushi** [comment]
> 联系我

?

**Comment by github-gsjb** [comment]
> > 联系我
> 
> ?
virtualapp

**Comment by mimajiushi** [comment]
> > > 联系我
> > 
> > 
> > ?
> > virtualapp

联系你干啥？

**Comment by github-gsjb** [comment]
> > > > 联系我
> > > 
> > > 
> > > ?
> > > virtualapp
> 
> 联系你干啥？

不是要解决包的问题？我有源码啊

**Comment by mimajiushi** [comment]
> 不是要解决包的问题？我有源码啊

哦豁，那要怎么联系

**Comment by github-gsjb** [comment]
> > 不是要解决包的问题？我有源码啊
> 
> 哦豁，那要怎么联系
你微信多少？我加你

**Comment by mimajiushi** [comment]
> > > 不是要解决包的问题？我有源码啊
> > 
> > 
> > 哦豁，那要怎么联系
> > 你微信多少？我加你

wxid_10124k199nj022

**Comment by github-gsjb** [comment]
> wxid_10124k199nj022

wxid 搜索不到的。。。。。。

**Comment by mimajiushi** [comment]
> > wxid_10124k199nj022
> 
> wxid 搜索不到的。。。。。。

改了，cwjstar1498
